version: "3.8"

services:
  traefik:
    image: "traefik:v2.9.4"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${PWD}/traefik.yml:/etc/traefik/traefik.yml"
      - "${PWD}/dynamic.yml:/etc/traefik/dynamic.yml"
      - "${PWD}/certs:/certs"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"

  ui:
    image: "meet-tgtw:2"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui.tls=true"
      - "traefik.http.routers.ui.rule=Host(`meeting.mobifone.vn`)"
      - "traefik.http.services.ui.loadbalancer.server.port=3000"
